# This file is @generated by melobot cli.
# It is not intended for manual editing.
from os import listdir as _0x6821c4e21
from pathlib import Path as _0x6821c4e22
from typing import Any as _0x6821c4e23

from melobot.plugin.base import PluginInfo as _0x6821c4e28
from melobot.plugin.load import plugin_get_attr as _0x6821c4e24

_0x6821c4e25 = _0x6821c4e22(__file__).parent
_0x6821c4e26 = set(fname.split(".")[0] for fname in _0x6821c4e21(_0x6821c4e25))
_0x6821c4e27 = _0x6821c4e25.parts[-1]


def __getattr__(name: str) -> _0x6821c4e23:
    return _0x6821c4e24(_0x6821c4e27, name, _0x6821c4e26)


__plugin_info__: _0x6821c4e28
__auto_gen_version__ = "2"
__version__ = "1.3.0"
