# This file is @generated by melobot cli.
# It is not intended for manual editing.
from os import listdir as _0x67949dcf1
from pathlib import Path as _0x67949dcf2
from typing import Any as _0x67949dcf3

from melobot import get_bot as _0x67949dcf4

_0x67949dcf5 = _0x67949dcf2(__file__).parent
_0x67949dcf6 = set(fname.split(".")[0] for fname in _0x67949dcf1(_0x67949dcf5))
_0x67949dcf7 = _0x67949dcf5.parts[-1]


def __getattr__(name: str) -> _0x67949dcf3:
    if name in _0x67949dcf6 or name.startswith("_"):
        raise AttributeError
    obj = _0x67949dcf4().get_share(_0x67949dcf7, name)
    if obj.static:
        return obj.get()
    return obj
