# This file is @generated by melobot cli.
# It is not intended for manual editing.
from os import listdir as _0x675ff1171
from pathlib import Path as _0x675ff1172
from typing import Any as _0x675ff1173

from melobot import get_bot as _0x675ff1174

_0x675ff1175 = _0x675ff1172(__file__).parent
_0x675ff1176 = set(fname.split(".")[0] for fname in _0x675ff1171(_0x675ff1175))
_0x675ff1177 = _0x675ff1175.parts[-1]


def __getattr__(name: str) -> _0x675ff1173:
    if name in _0x675ff1176 or name.startswith("_"):
        raise AttributeError
    obj = _0x675ff1174().get_share(_0x675ff1177, name)
    if obj.static:
        return obj.get()
    return obj
